### ISSUE TITLE
Handle get_map_url on multiple canvases 

### ISSUE THREAD

**Issue by goatgoose** [goatgoose/PlaceBot#12]
`_get_map_url` currently only works on the first canvas. Figure out how the js is requesting the second canvas URL and replicate the websocket sends. Additionally, `_get_map_url` should take the canvas id as an argument, and only the relevant canvas should be queried in `maintain_image`.

**Comment by Ziegenkaese** [comment]
Hello, 
I dont want to be a total parasite so here is my tiny contribution.

in  `_get_map_url`,
if you change the value of `tag` under `channel` from 0 to 1, then you will get the data from the second canvas. 
The way I did it last night is to just call `_get_map_url` twice and then concatenate the data of each canvas together into one. That way I can draw on the second canvas.

Not a perfect solution, but works for me.

**Comment by goatgoose** [comment]
That works! Thanks for the comment!
