### ISSUE TITLE
Feature request: support arbitrary color images by converting inside python.

### ISSUE THREAD

**Issue by laundmo** [goatgoose/PlaceBot#4]
MVP: convert only EXACT hex values by either loading the ACT or storing the values in python.

later: convert any color by finding the closest from the color table

**Comment by goatgoose** [comment]
Yeah, this is a good idea. Currently I'm saving the images in an indexed color mode rather than RGB, but converting to the index from RGB via exact hex values would make creating images easier for sure.

**Comment by laundmo** [comment]
actually i might PR this, since im the one who needs it

**Comment by laundmo** [comment]
addressed in #7

**Comment by laundmo** [comment]
closed by #7
