### ISSUE TITLE
Question: How to make indexed PNGs without Adobe Photoshop

### ISSUE THREAD

**Issue by laundmo** [goatgoose/PlaceBot#5]
I dont own photoshop, and other ways to convert pngs to indexed seem hard to come by.

Would you know how to convert without access to adobe products?

related to: #4

**Comment by goatgoose** [comment]
I imagine there's something similar in GIMP, but I'm not sure. In photoshop you basically create the image and then convert the mode to indexed color, and then upload the .act in the repo, and the resulting png is all indices corresponding to each color.

#4 is a good idea, it's probably the easiest way to avoid this.

**Comment by laundmo** [comment]
closing because indexed pngs are no longer necessary
